### ISSUE TITLE
Do git pair commits included in contributions graph?

### ISSUE THREAD

**Issue by vinamelody** [pivotal/git_scripts#42]
Hi, sorry this isn't really an issue but out of curiosity since I've been using this for about a month now but I can't see the count on my graph.
Thanks for clarifying.

**Comment by textbook** [comment]
They should be, if: 

 1. You have the `.pairs` file configured correctly, so that it's using an email address [connected to your GitHub account](https://help.github.com/articles/adding-an-email-address-to-your-github-account/); 

 2. You're using `git-pair-commit` to commit, so that it picks one author's email address for each commit rather than using the generated email address with your initials in; and 

 3. The repo is public or you've [configured GitHub to include private contributions](https://github.com/blog/2173-more-contributions-on-your-profile).

You can check the emails on existing commits with e.g. `git log --pretty=format:"%h %ae"`.

**Comment by vinamelody** [comment]
I see ... I notice it on GitHub enterprise. Apparently, I have .pairs file configured so the history would show both names but never commit using `git-pair-commit` LOL ... 
Besides, most of the time, I'm using SourceTree. I will try to stage files using SourceTree, try `git-pair-commit` next week and let you know again :)

**Comment by tjarratt** [comment]
Yes, @textbook is correct, this does work, so long as you use an email address that is associated with your github account.

Some people alias `git-pair-commit` to a command that is easier to remember (and type), for example `git ci`

~/.gitconfig
```
[alias]
	ci = pair-commit
```

**Comment by tjarratt** [comment]
@vinamelody can we close this issue? Or is there more we could do to help out?

**Comment by vinamelody** [comment]
@tjarratt yup sure!

**Comment by nertzy** [comment]
FYI You can also have multiple emails associated with your GitHub account if you want.

https://github.com/settings/emails
